services:
  web:
    image: dkorolev13/test:9
    container_name: "django_container"
    # Берем Dockerfile из каталога app
    build:
      context: .
      dockerfile: Dockerfile



    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000

    # куда будут помещены данные из каталога app
    volumes:
      - ./web:/usr/src/web/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8881:8000
    # Файл содержащий переменные для контейнера

