services:
  web:
    image: dkorolev13/test:2
    container_name: "django_container"
    # Берем Dockerfile из каталога app


    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000

    # куда будут помещены данные из каталога app
    volumes:
      - ./web:/usr/src/app/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8802:8000
    # Файл содержащий переменные для контейнера

