services:
  web:
    # Берем Dockerfile из каталога app
    build: .

    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000

    # куда будут помещены данные из каталога app
    volumes:
      - ./web:/usr/src/app/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8801:8000
    # Файл содержащий переменные для контейнера

